name: papers_test_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path: ^1.8.3
  path_provider: ^2.1.1
  syncfusion_flutter_pdfviewer: ^22.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/olevel_subjects.json
    - assets/alevel_subjects.json
    - assets/icons/
    - assets/images/